### ISSUE TITLE
Looking for New Maintainer

### ISSUE THREAD

**Issue by benhansen-io** [benhansen-io/BigCtrl#2]
Hi everyone. I am no longer using Windows or Emacs on a regular basis. Accordingly, I am no longer maintaining this project. If anyone is interested in taking on maintenance/development I would be happy to transfer the repository over to your account or reference your repository as the new central repository. I have occasionally received emails from users with various problems. I will post them in the issue tracker here for reference.

**Comment by lydell** [comment]
Hi, I'm the author of [dual](https://github.com/lydell/dual), which let's you define dual-role keys in general. Here is an implementation of BigCtrl using it:

``` ahk
SendMode Input
#NoEnv
#SingleInstance force

#Include <dual/dual>
dual := new Dual

#Include <dual/defaults>

#If true ; Override defaults.ahk. There will be "duplicate hotkey" errors otherwise.

*Space::
*Space UP::dual.combine("RCtrl", A_ThisHotkey)

#If

*ScrollLock::dual.reset()
```

So perhaps I already am a "maintainer" of this project?

**Comment by benhansen-io** [comment]
Awesome! I just looked over the code and did a quick test and it all looks very well done. I will change the readme to direct new users to your project. Keep up the good work!
